# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.8.1'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is an LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end


module Parselly
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 255)
def parse(input)
  @lexer = Parselly::Lexer.new(input)
  @tokens = @lexer.tokenize
  preprocess_tokens!
  @index = 0
  @current_position = { line: 1, column: 1 }
  ast = do_parse
  normalize_an_plus_b(ast)
  ast
end

def preprocess_tokens!
  new_tokens = []
  i = 0
  while i < @tokens.size
    token = @tokens[i]
    next_token = @tokens[i + 1]
    new_tokens << token
    if next_token && needs_descendant?(token, next_token)
      pos = { line: token[2][:line], column: token[2][:column] }
      new_tokens << [:DESCENDANT, ' ', pos]
    end
    i += 1
  end

  @tokens = new_tokens
end

# Insert DESCENDANT combinator if:
# - Current token can end a compound selector
# - Next token can start a compound selector
# - EXCEPT when current is type_selector and next is subclass_selector
#   (they belong to the same compound selector)
def needs_descendant?(current, next_tok)
  current_type = current[0]
  next_type = next_tok[0]

  can_end = can_end_compound?(current_type)
  can_start = can_start_compound?(next_type)

  # Type selector followed by subclass selector = same compound
  if [:IDENT, :STAR].include?(current_type) &&
     [:DOT, :HASH, :LBRACKET, :COLON].include?(next_type)
    return false
  end

  can_end && can_start
end

def can_end_compound?(token_type)
  [:IDENT, :STAR, :RPAREN, :RBRACKET].include?(token_type)
end

def can_start_compound?(token_type)
  # Type selectors and subclass selectors can start a compound selector
  [:IDENT, :STAR, :DOT, :HASH, :LBRACKET, :COLON].include?(token_type)
end

def normalize_an_plus_b(node)
  return unless node.respond_to?(:children) && node.children

  if node.type == :pseudo_function && nth_pseudo?(node.value)
    child = node.children.first
    if child && child.type == :selector_list
      an_plus_b_value = extract_an_plus_b_value(child)
      if an_plus_b_value
        node.children[0] = Node.new(:an_plus_b, an_plus_b_value, child.position)
      end
    end
  end
  node.children.compact.each { |child| normalize_an_plus_b(child) }
end

def nth_pseudo?(name)
  %w[nth-child nth-last-child nth-of-type nth-last-of-type nth-col nth-last-col].include?(name)
end

def extract_an_plus_b_value(selector_list_node)
  return nil unless selector_list_node.children.size == 1

  seq = selector_list_node.children.first
  return nil unless seq.type == :simple_selector_sequence
  return nil unless seq.children.size == 1

  type_sel = seq.children.first
  return nil unless type_sel.type == :type_selector

  value = type_sel.value
  if value =~ /^(even|odd|[+-]?\d*n(?:[+-]\d+)?|[+-]?n(?:[+-]\d+)?|\d+)$/
    value
  else
    nil
  end
end

def next_token
  return [false, nil] if @index >= @tokens.size

  token_type, token_value, token_position = @tokens[@index]
  @index += 1
  @current_position = token_position

  [token_type, token_value]
end

def on_error(token_id, val, vstack)
  token_name = token_to_str(token_id) || '?'
  pos = @current_position || { line: '?', column: '?' }
  raise "Parse error: unexpected #{token_name} '#{val}' at #{pos[:line]}:#{pos[:column]}"
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    48,    50,    53,    14,    15,     8,    16,    29,    18,    59,
    17,    26,    21,    22,    23,    24,    27,    30,    60,    70,
     7,    19,    54,    14,    15,     8,    16,    35,    71,    65,
    17,    64,    21,    22,    23,    24,    37,    38,    39,    40,
    41,    42,     7,    46,    45,    14,    15,     8,    16,    28,
     7,    31,    17,    14,    15,     8,    16,    43,     7,    44,
    17,    14,    15,     8,    16,    73,     7,    57,    17,    14,
    15,     8,    16,    77,    74,    58,    17,    14,    15,    61,
    16,    62,    78,    63,    17,    21,    22,    23,    24,    21,
    22,    23,    24,    21,    22,    23,    24,    21,    22,    23,
    24,    67,    68,    72,    75,    76,    79,    80,    81,    82 ]

racc_action_check = [
    43,    43,    43,    43,    43,    43,    43,    17,     1,    48,
    43,    14,    43,    43,    43,    43,    15,    17,    48,    63,
    62,     1,    43,    62,    62,    62,    62,    28,    63,    54,
    62,    54,    62,    62,    62,    62,    28,    28,    28,    28,
    28,    28,     0,    36,    36,     0,     0,     0,     0,    16,
    19,    18,     0,    19,    19,    19,    19,    29,    20,    30,
    19,    20,    20,    20,    20,    65,    56,    45,    20,    56,
    56,    56,    56,    72,    65,    46,    56,    25,    25,    49,
    25,    52,    72,    53,    25,     2,     2,     2,     2,    32,
    32,    32,    32,    47,    47,    47,    47,    66,    66,    66,
    66,    59,    60,    64,    70,    71,    73,    74,    77,    78 ]

racc_action_pointer = [
    40,     8,    71,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     9,    14,    47,     5,    51,    48,
    56,   nil,   nil,   nil,   nil,    72,   nil,   nil,    18,    47,
    57,   nil,    75,   nil,   nil,   nil,    41,   nil,   nil,   nil,
   nil,   nil,   nil,    -2,   nil,    58,    66,    79,    -6,    68,
   nil,   nil,    68,    81,    27,   nil,    64,   nil,   nil,    97,
    98,   nil,    18,     4,   101,    50,    83,   nil,   nil,   nil,
   100,   101,    58,   102,   103,   nil,   nil,   104,   105,   nil,
   nil,   nil,   nil ]

racc_action_default = [
   -54,   -54,    -1,    -3,   -12,   -10,   -11,   -14,   -15,   -16,
   -17,   -18,   -19,   -20,   -54,   -54,   -54,   -54,   -54,   -54,
   -54,    -5,    -6,    -7,    -8,    -9,   -21,   -22,   -54,   -32,
   -54,    83,    -2,    -4,   -13,   -23,   -54,   -26,   -27,   -28,
   -29,   -30,   -31,   -54,   -34,   -54,   -54,   -52,   -14,   -54,
   -35,   -36,   -37,   -49,   -54,   -50,   -54,   -24,   -25,   -54,
   -54,   -33,   -54,   -40,   -54,   -48,   -53,   -41,   -42,   -51,
   -54,   -54,   -45,   -54,   -54,   -38,   -39,   -54,   -54,   -46,
   -47,   -43,   -44 ]

racc_goto_table = [
     2,    56,    55,     1,    33,    25,    34,    36,    49,    51,
    52,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    32,
    56,    69,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    66 ]

racc_goto_check = [
     2,     4,    18,     1,     3,     6,     8,    14,    15,    16,
    17,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,
     4,    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     3,     0,   -16,   -42,   nil,     1,   nil,   -19,   nil,
   nil,   nil,   nil,   nil,   -21,   -35,   -34,   -33,   -41 ]

racc_goto_default = [
   nil,   nil,    47,     3,    20,     4,   nil,     5,     6,     9,
    10,    11,    12,    13,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 26, :_reduce_1,
  3, 26, :_reduce_2,
  1, 27, :_reduce_3,
  3, 27, :_reduce_4,
  1, 29, :_reduce_5,
  1, 29, :_reduce_6,
  1, 29, :_reduce_7,
  1, 29, :_reduce_8,
  2, 28, :_reduce_9,
  1, 30, :_reduce_10,
  1, 30, :_reduce_11,
  0, 31, :_reduce_12,
  2, 31, :_reduce_13,
  1, 32, :_reduce_14,
  1, 32, :_reduce_15,
  1, 33, :_reduce_16,
  1, 33, :_reduce_17,
  1, 33, :_reduce_18,
  1, 33, :_reduce_19,
  1, 33, :_reduce_20,
  2, 34, :_reduce_21,
  2, 35, :_reduce_22,
  3, 36, :_reduce_23,
  5, 36, :_reduce_24,
  5, 36, :_reduce_25,
  1, 39, :_reduce_26,
  1, 39, :_reduce_27,
  1, 39, :_reduce_28,
  1, 39, :_reduce_29,
  1, 39, :_reduce_30,
  1, 39, :_reduce_31,
  2, 37, :_reduce_32,
  5, 37, :_reduce_33,
  3, 38, :_reduce_34,
  1, 40, :_reduce_35,
  1, 40, :_reduce_36,
  1, 40, :_reduce_37,
  4, 41, :_reduce_38,
  4, 41, :_reduce_39,
  2, 41, :_reduce_40,
  3, 41, :_reduce_41,
  3, 41, :_reduce_42,
  5, 41, :_reduce_43,
  5, 41, :_reduce_44,
  3, 41, :_reduce_45,
  4, 41, :_reduce_46,
  4, 41, :_reduce_47,
  2, 41, :_reduce_48,
  1, 41, :_reduce_49,
  1, 42, :_reduce_50,
  3, 42, :_reduce_51,
  1, 43, :_reduce_52,
  2, 43, :_reduce_53 ]

racc_reduce_n = 54

racc_shift_n = 83

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENT => 2,
  :STRING => 3,
  :NUMBER => 4,
  :HASH => 5,
  :DOT => 6,
  :STAR => 7,
  :LBRACKET => 8,
  :RBRACKET => 9,
  :LPAREN => 10,
  :RPAREN => 11,
  :COLON => 12,
  :COMMA => 13,
  :CHILD => 14,
  :ADJACENT => 15,
  :SIBLING => 16,
  :DESCENDANT => 17,
  :EQUAL => 18,
  :INCLUDES => 19,
  :DASHMATCH => 20,
  :PREFIXMATCH => 21,
  :SUFFIXMATCH => 22,
  :SUBSTRINGMATCH => 23,
  :MINUS => 24 }

racc_nt_base = 25

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENT",
  "STRING",
  "NUMBER",
  "HASH",
  "DOT",
  "STAR",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "COLON",
  "COMMA",
  "CHILD",
  "ADJACENT",
  "SIBLING",
  "DESCENDANT",
  "EQUAL",
  "INCLUDES",
  "DASHMATCH",
  "PREFIXMATCH",
  "SUFFIXMATCH",
  "SUBSTRINGMATCH",
  "MINUS",
  "$start",
  "selector_list",
  "complex_selector",
  "compound_selector",
  "combinator",
  "simple_selector_head",
  "simple_selector_tail",
  "type_selector",
  "subclass_selector",
  "id_selector",
  "class_selector",
  "attribute_selector",
  "pseudo_class_selector",
  "pseudo_element_selector",
  "attr_matcher",
  "any_value",
  "an_plus_b",
  "relative_selector_list",
  "relative_selector" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_1(val, _values, result)
     result = Node.new(:selector_list, nil, @current_position); result.add_child(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 27)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_child(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_3(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_4(val, _values, result)
            result = Node.new(:selector, nil, val[0].position)
        result.add_child(val[0])
        result.add_child(val[1])
        result.add_child(val[2])

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_5(val, _values, result)
     result = Node.new(:child_combinator, '>', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 46)
  def _reduce_6(val, _values, result)
     result = Node.new(:adjacent_combinator, '+', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_7(val, _values, result)
     result = Node.new(:sibling_combinator, '~', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_8(val, _values, result)
     result = Node.new(:descendant_combinator, ' ', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_9(val, _values, result)
            result = Node.new(:simple_selector_sequence, nil, val[0].position)
        result.add_child(val[0])
        val[1].each { |sel| result.add_child(sel) } unless val[1].empty?

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_10(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_11(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 71)
  def _reduce_12(val, _values, result)
     result = []
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 73)
  def _reduce_13(val, _values, result)
     result = val[0]; result << val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_14(val, _values, result)
     result = Node.new(:type_selector, val[0], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 80)
  def _reduce_15(val, _values, result)
     result = Node.new(:universal_selector, '*', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 85)
  def _reduce_16(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 87)
  def _reduce_17(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 89)
  def _reduce_18(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_20(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_21(val, _values, result)
     result = Node.new(:id_selector, val[1], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 103)
  def _reduce_22(val, _values, result)
     result = Node.new(:class_selector, val[1], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 108)
  def _reduce_23(val, _values, result)
     result = Node.new(:attribute_selector, val[1], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 111)
  def _reduce_24(val, _values, result)
            result = Node.new(:attribute_selector, nil, @current_position)
        result.add_child(Node.new(:attribute, val[1], @current_position))
        result.add_child(val[2])
        result.add_child(Node.new(:value, val[3], @current_position))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 118)
  def _reduce_25(val, _values, result)
            result = Node.new(:attribute_selector, nil, @current_position)
        result.add_child(Node.new(:attribute, val[1], @current_position))
        result.add_child(val[2])
        result.add_child(Node.new(:value, val[3], @current_position))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 127)
  def _reduce_26(val, _values, result)
     result = Node.new(:equal_operator, '=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 129)
  def _reduce_27(val, _values, result)
     result = Node.new(:includes_operator, '~=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 131)
  def _reduce_28(val, _values, result)
     result = Node.new(:dashmatch_operator, '|=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_29(val, _values, result)
     result = Node.new(:prefixmatch_operator, '^=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 135)
  def _reduce_30(val, _values, result)
     result = Node.new(:suffixmatch_operator, '$=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 137)
  def _reduce_31(val, _values, result)
     result = Node.new(:substringmatch_operator, '*=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 142)
  def _reduce_32(val, _values, result)
     result = Node.new(:pseudo_class, val[1], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 145)
  def _reduce_33(val, _values, result)
            fn = Node.new(:pseudo_function, val[1], @current_position)
        fn.add_child(val[3])
        result = fn

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 153)
  def _reduce_34(val, _values, result)
     result = Node.new(:pseudo_element, val[2], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 158)
  def _reduce_35(val, _values, result)
     result = Node.new(:argument, val[0], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 160)
  def _reduce_36(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 162)
  def _reduce_37(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 169)
  def _reduce_38(val, _values, result)
            # Handle 'An+B' like '2n+1'
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}+#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 174)
  def _reduce_39(val, _values, result)
            # Handle 'An-B' like '2n-1'
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}-#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 179)
  def _reduce_40(val, _values, result)
            # Handle 'An' like '2n' or composite like '2n-1' (when '-1' is part of IDENT)
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 184)
  def _reduce_41(val, _values, result)
            # Handle 'n+B' like 'n+5' or keywords followed by offset (rare but valid)
        result = Node.new(:an_plus_b, "#{val[0]}+#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 189)
  def _reduce_42(val, _values, result)
            # Handle 'n-B' like 'n-3'
        result = Node.new(:an_plus_b, "#{val[0]}-#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 195)
  def _reduce_43(val, _values, result)
            # Handle '-An+B' like '-2n+1'
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}+#{val[4]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 200)
  def _reduce_44(val, _values, result)
            # Handle '-An-B' like '-2n-1'
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}-#{val[4]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 205)
  def _reduce_45(val, _values, result)
            # Handle '-An' like '-2n' or composite like '-2n+1' (when '+1' is part of IDENT)
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 210)
  def _reduce_46(val, _values, result)
            # Handle '-n+B' like '-n+3'
        result = Node.new(:an_plus_b, "-#{val[1]}+#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 215)
  def _reduce_47(val, _values, result)
            # Handle '-n-B' like '-n-2'
        result = Node.new(:an_plus_b, "-#{val[1]}-#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 220)
  def _reduce_48(val, _values, result)
            # Handle '-n' or composite like '-n+3' (when '+3' is part of IDENT)
        result = Node.new(:an_plus_b, "-#{val[1]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 226)
  def _reduce_49(val, _values, result)
            # Handle just a number like '3'
        result = Node.new(:an_plus_b, val[0].to_s, @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 233)
  def _reduce_50(val, _values, result)
     result = Node.new(:selector_list, nil, @current_position); result.add_child(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 235)
  def _reduce_51(val, _values, result)
     result = val[0]; result.add_child(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 240)
  def _reduce_52(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 243)
  def _reduce_53(val, _values, result)
            result = Node.new(:selector, nil, val[0].position)
        result.add_child(val[0])
        result.add_child(val[1])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Parselly
