# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

###### racc/parser.rb begin
unless $".find {|p| p.end_with?('/racc/parser.rb')}
$".push "#{__dir__}/racc/parser.rb"
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#--
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#++

unless $".find {|p| p.end_with?('/racc/info.rb')}
$".push "#{__dir__}/racc/info.rb"

module Racc
  VERSION   = '1.8.1'
  Version = VERSION
  Copyright = 'Copyright (c) 1999-2006 Minero Aoki'
end

end


module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError # :nodoc:
end

# Racc is an LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--executable=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+grammarfile+]
#   Racc grammar file. Any extension is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debugging information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-F, --frozen]
#   Output parser which declares frozen_string_literals: true
# [-C, --check-only]
#   Check syntax of racc grammar file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is ruby license, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extensions)
    Racc_No_Extensions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Core_Version_R = ::Racc::VERSION

    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end

      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extensions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def do_parse
      #{Racc_Main_Parsing_Routine}(_racc_setup(), false)
    end
    RUBY

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    class_eval <<~RUBY, __FILE__, __LINE__ + 1
    def yyparse(recv, mid)
      #{Racc_YY_Parse_Method}(recv, mid, _racc_setup(), false)
    end
    RUBY

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("parse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is +Symbol_Value_Stack[0]+.
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end

require 'set'

# Pre-computed sets for faster lookup
CAN_END_COMPOUND = Set[:IDENT, :STAR, :RPAREN, :RBRACKET].freeze
CAN_START_COMPOUND = Set[:IDENT, :STAR, :DOT, :HASH, :LBRACKET, :COLON].freeze
TYPE_SELECTOR_TYPES = Set[:IDENT, :STAR].freeze
SUBCLASS_SELECTOR_TYPES = Set[:DOT, :HASH, :LBRACKET, :COLON].freeze
SUBCLASS_SELECTOR_END_TYPES = Set[:IDENT, :RBRACKET, :RPAREN].freeze
NTH_PSEUDO_NAMES = Set['nth-child', 'nth-last-child', 'nth-of-type', 'nth-last-of-type', 'nth-col', 'nth-last-col'].freeze
AN_PLUS_B_REGEX = /^(even|odd|[+-]?\d*n(?:[+-]\d+)?|[+-]?n(?:[+-]\d+)?|\d+)$/.freeze

module Parselly
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 279)
def parse(input, tolerant: false)
  @tolerant = tolerant
  @errors = []
  @error_index = nil
  @suppress_errors = false
  @lexer = Parselly::Lexer.new(input)
  begin
    @tokens = @lexer.tokenize
  rescue RuntimeError => e
    if tolerant
      @errors << parse_error_from_exception(e)
      return Parselly::ParseResult.new(nil, @errors)
    end
    raise
  end
  preprocess_tokens!
  @index = 0
  @current_position = { line: 1, column: 1 }

  if tolerant
    ast = parse_with_recovery
    normalize_an_plus_b(ast) if ast
    return Parselly::ParseResult.new(ast, @errors)
  end

  ast = do_parse
  normalize_an_plus_b(ast)
  ast
end

def parse_with_recovery
  do_parse
rescue Parselly::ParseError, RuntimeError
  parse_partial_ast
end

def parse_partial_ast
  return nil unless @tokens && !@tokens.empty?

  eof_token = @tokens.last if @tokens.last && @tokens.last[0] == false
  tokens = @tokens.dup
  tokens.pop if eof_token
  limit = @error_index || tokens.length

  while limit > 0
    truncated = tokens[0...limit]
    truncated << eof_token if eof_token
    begin
      return parse_from_tokens(truncated, suppress_errors: true)
    rescue Parselly::ParseError, RuntimeError
      limit -= 1
    end
  end
  nil
end

def parse_from_tokens(tokens, suppress_errors: false)
  @tokens = tokens
  @index = 0
  @current_position = { line: 1, column: 1 }
  @suppress_errors = suppress_errors
  do_parse
ensure
  @suppress_errors = false
end

def parse_error_from_exception(error)
  line = nil
  column = nil
  if error.message =~ /at (\d+):(\d+)/
    line = Regexp.last_match(1).to_i
    column = Regexp.last_match(2).to_i
  end
  { message: error.message, line: line, column: column }
end

def identifier_value(token)
  token.respond_to?(:value) ? token.value : token
end

def identifier_raw(token)
  token.respond_to?(:raw) ? token.raw : token
end

def preprocess_tokens!
  return if @tokens.size <= 1

  new_tokens = Array.new(@tokens.size + (@tokens.size / 2)) # Pre-allocate with conservative estimate
  new_tokens_idx = 0

  last_idx = @tokens.size - 1
  @tokens.each_with_index do |token, i|
    new_tokens[new_tokens_idx] = token
    new_tokens_idx += 1

    if i < last_idx
      next_token = @tokens[i + 1]
      if needs_descendant?(token, next_token)
        pos = { line: token[2][:line], column: token[2][:column] }
        new_tokens[new_tokens_idx] = [:DESCENDANT, ' ', pos]
        new_tokens_idx += 1
      end
    end
  end

  @tokens = new_tokens.first(new_tokens_idx)
end

# Insert DESCENDANT combinator if:
# - Current token can end a compound selector
# - Next token can start a compound selector
# - EXCEPT when current is type_selector and next is subclass_selector
#   (they belong to the same compound selector)
def needs_descendant?(current, next_tok)
  current_type = current[0]
  next_type = next_tok[0]

  # Type selector followed by subclass selector = same compound
  # Subclass selector followed by subclass selector = same compound
  if SUBCLASS_SELECTOR_TYPES.include?(next_type)
    return false if TYPE_SELECTOR_TYPES.include?(current_type) ||
                    SUBCLASS_SELECTOR_END_TYPES.include?(current_type)
  end

  CAN_END_COMPOUND.include?(current_type) && CAN_START_COMPOUND.include?(next_type)
end

def normalize_an_plus_b(node)
  return unless node.respond_to?(:children) && node.children

  if node.type == :pseudo_function && NTH_PSEUDO_NAMES.include?(node.value)
    child = node.children.first
    if child&.type == :selector_list
      an_plus_b_value = extract_an_plus_b_value(child)
      if an_plus_b_value
        node.replace_child(0, Node.new(:an_plus_b, an_plus_b_value, child.position))
      end
    end
  end
  node.children.compact.each { |child| normalize_an_plus_b(child) }
end

def extract_an_plus_b_value(selector_list_node)
  return nil unless selector_list_node.children.size == 1

  seq = selector_list_node.children.first
  return nil unless seq.type == :simple_selector_sequence && seq.children.size == 1

  type_sel = seq.children.first
  return nil unless type_sel.type == :type_selector

  value = type_sel.value
  value if value =~ AN_PLUS_B_REGEX
end

def next_token
  return [false, nil] if @index >= @tokens.size

  token_type, token_value, token_position = @tokens[@index]
  @index += 1
  @current_position = token_position

  [token_type, token_value]
end

def on_error(token_id, val, vstack)
  token_name = token_to_str(token_id) || '?'
  pos = @current_position || { line: '?', column: '?' }
  error = {
    message: "Parse error: unexpected #{token_name} '#{val}' at #{pos[:line]}:#{pos[:column]}",
    line: pos[:line],
    column: pos[:column]
  }
  if @tolerant
    @errors << error unless @suppress_errors
    @error_index ||= [@index - 1, 0].max
    raise Parselly::ParseError, error
  end
  raise error[:message]
end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    45,    47,    50,    14,    15,     8,    16,    55,    18,    70,
    17,    69,    25,    26,    27,    28,    57,    58,    59,    60,
    61,    62,    51,    45,    47,    50,    14,    15,     8,    16,
    37,    19,    80,    17,    33,    25,    26,    27,    28,    34,
    38,    81,    83,     7,    35,    51,    14,    15,     8,    16,
    36,    84,    92,    17,    33,    25,    26,    27,    28,    65,
     7,    93,    39,    14,    15,     8,    16,    19,    66,    32,
    17,    33,    14,    15,    63,    16,    64,     7,    67,    17,
    14,    15,     8,    16,    68,     7,    71,    17,    14,    15,
     8,    16,    78,    32,    79,    17,    14,    15,    82,    16,
    71,     7,    87,    17,    14,    15,     8,    16,    76,    75,
    88,    17,    25,    26,    27,    28,    25,    26,    27,    28,
    89,    90,    91,    94,    95,    96,    97 ]

racc_action_check = [
    33,    33,    33,    33,    33,    33,    33,    36,     1,    51,
    33,    51,    33,    33,    33,    33,    36,    36,    36,    36,
    36,    36,    33,    63,    63,    63,    63,    63,    63,    63,
    17,     2,    68,    63,     7,    63,    63,    63,    63,    14,
    17,    68,    70,    71,    15,    63,    71,    71,    71,    71,
    16,    70,    82,    71,    45,    71,    71,    71,    71,    45,
     0,    82,    18,     0,     0,     0,     0,    20,    45,     4,
     0,    32,     4,     4,    37,     4,    38,    19,    46,     4,
    19,    19,    19,    19,    50,    22,    52,    19,    22,    22,
    22,    22,    65,    30,    66,    22,    30,    30,    69,    30,
    72,    54,    75,    30,    54,    54,    54,    54,    56,    56,
    76,    54,     3,     3,     3,     3,    23,    23,    23,    23,
    77,    80,    81,    83,    84,    92,    93 ]

racc_action_pointer = [
    58,     8,    18,    98,    67,   nil,   nil,    24,   nil,   nil,
   nil,   nil,   nil,   nil,    37,    42,    48,    28,    62,    75,
    54,   nil,    83,   102,   nil,   nil,   nil,   nil,   nil,   nil,
    91,   nil,    61,    -2,   nil,   nil,    -2,    64,    74,   nil,
   nil,   nil,   nil,   nil,   nil,    44,    67,   nil,   nil,   nil,
    82,     7,    73,   nil,    99,   nil,   106,   nil,   nil,   nil,
   nil,   nil,   nil,    21,   nil,    88,    90,   nil,    17,    96,
    27,    41,    87,   nil,   nil,    93,   101,   109,   nil,   nil,
   117,   118,    37,   119,   120,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   121,   122,   nil,   nil,   nil,   nil ]

racc_action_default = [
   -62,   -62,    -2,    -6,   -16,   -14,   -15,   -19,   -20,   -21,
   -22,   -23,   -24,   -25,   -62,   -62,   -62,   -62,   -62,   -62,
    -2,    -4,   -62,    -6,    -8,    -9,   -10,   -11,   -12,   -13,
   -16,   -18,   -62,   -62,   -26,   -27,   -62,   -37,   -62,    98,
    -1,    -3,    -5,    -7,   -17,   -19,   -62,   -41,   -42,   -43,
   -55,   -62,   -57,   -60,   -62,   -28,   -62,   -31,   -32,   -33,
   -34,   -35,   -36,   -62,   -40,   -62,   -62,   -39,   -46,   -62,
   -54,   -62,   -57,   -59,   -61,   -62,   -62,   -62,   -47,   -48,
   -62,   -62,   -51,   -62,   -62,   -56,   -58,   -29,   -30,   -38,
   -44,   -45,   -62,   -62,   -52,   -53,   -49,   -50 ]

racc_goto_table = [
     2,    46,    30,    31,    22,    24,    73,     1,    42,    21,
    29,    56,    85,   nil,   nil,   nil,   nil,   nil,   nil,    40,
   nil,   nil,   nil,   nil,    22,    43,    86,    41,    30,    44,
   nil,    77,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    74 ]

racc_goto_check = [
     2,    20,    12,    13,     6,     8,    25,     1,     5,     4,
    10,    19,    23,   nil,   nil,   nil,   nil,   nil,   nil,     2,
   nil,   nil,   nil,   nil,     6,     8,    25,     4,    12,    13,
   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     2 ]

racc_goto_pointer = [
   nil,     7,     0,   nil,     7,   -14,     1,   nil,     2,   nil,
     6,   nil,    -2,    -1,   nil,   nil,   nil,   nil,   nil,   -25,
   -32,   nil,   nil,   -59,   nil,   -46 ]

racc_goto_default = [
   nil,   nil,    53,    20,   nil,     3,    54,    23,   nil,     4,
   nil,     5,     6,   nil,     9,    10,    11,    12,    13,   nil,
   nil,    48,    49,    52,    72,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 29, :_reduce_1,
  0, 30, :_reduce_2,
  2, 30, :_reduce_3,
  2, 27, :_reduce_4,
  2, 33, :_reduce_5,
  0, 34, :_reduce_6,
  2, 34, :_reduce_7,
  2, 28, :_reduce_8,
  1, 32, :_reduce_9,
  1, 32, :_reduce_10,
  1, 32, :_reduce_11,
  1, 32, :_reduce_12,
  2, 31, :_reduce_13,
  1, 35, :_reduce_14,
  1, 35, :_reduce_15,
  0, 39, :_reduce_16,
  2, 39, :_reduce_17,
  1, 36, :_reduce_18,
  1, 37, :_reduce_19,
  1, 37, :_reduce_20,
  1, 38, :_reduce_21,
  1, 38, :_reduce_22,
  1, 38, :_reduce_23,
  1, 38, :_reduce_24,
  1, 38, :_reduce_25,
  2, 40, :_reduce_26,
  2, 41, :_reduce_27,
  3, 42, :_reduce_28,
  5, 42, :_reduce_29,
  5, 42, :_reduce_30,
  1, 45, :_reduce_31,
  1, 45, :_reduce_32,
  1, 45, :_reduce_33,
  1, 45, :_reduce_34,
  1, 45, :_reduce_35,
  1, 45, :_reduce_36,
  2, 43, :_reduce_37,
  5, 43, :_reduce_38,
  4, 43, :_reduce_39,
  3, 44, :_reduce_40,
  1, 46, :_reduce_41,
  1, 46, :_reduce_42,
  1, 46, :_reduce_43,
  4, 47, :_reduce_44,
  4, 47, :_reduce_45,
  2, 47, :_reduce_46,
  3, 47, :_reduce_47,
  3, 47, :_reduce_48,
  5, 47, :_reduce_49,
  5, 47, :_reduce_50,
  3, 47, :_reduce_51,
  4, 47, :_reduce_52,
  4, 47, :_reduce_53,
  2, 47, :_reduce_54,
  1, 47, :_reduce_55,
  2, 50, :_reduce_56,
  0, 51, :_reduce_57,
  2, 51, :_reduce_58,
  2, 48, :_reduce_59,
  1, 49, :_reduce_60,
  2, 49, :_reduce_61 ]

racc_reduce_n = 62

racc_shift_n = 98

racc_token_table = {
  false => 0,
  :error => 1,
  :IDENT => 2,
  :STRING => 3,
  :NUMBER => 4,
  :HASH => 5,
  :DOT => 6,
  :STAR => 7,
  :LBRACKET => 8,
  :RBRACKET => 9,
  :LPAREN => 10,
  :RPAREN => 11,
  :COLON => 12,
  :COMMA => 13,
  :CHILD => 14,
  :ADJACENT => 15,
  :SIBLING => 16,
  :DESCENDANT => 17,
  :EQUAL => 18,
  :INCLUDES => 19,
  :DASHMATCH => 20,
  :PREFIXMATCH => 21,
  :SUFFIXMATCH => 22,
  :SUBSTRINGMATCH => 23,
  :MINUS => 24,
  "-temp-group" => 25 }

racc_nt_base = 26

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "IDENT",
  "STRING",
  "NUMBER",
  "HASH",
  "DOT",
  "STAR",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "COLON",
  "COMMA",
  "CHILD",
  "ADJACENT",
  "SIBLING",
  "DESCENDANT",
  "EQUAL",
  "INCLUDES",
  "DASHMATCH",
  "PREFIXMATCH",
  "SUFFIXMATCH",
  "SUBSTRINGMATCH",
  "MINUS",
  "\"-temp-group\"",
  "$start",
  "selector_list",
  "complex_selector",
  "\"-group@COMMA-complex_selector\"",
  "\"-many@-group@COMMA-complex_selector\"",
  "compound_selector",
  "combinator",
  "\"-group@combinator-compound_selector\"",
  "\"-many@-group@combinator-compound_selector\"",
  "simple_selector_head",
  "simple_selector_tail",
  "type_selector",
  "subclass_selector",
  "\"-many@subclass_selector\"",
  "id_selector",
  "class_selector",
  "attribute_selector",
  "pseudo_class_selector",
  "pseudo_element_selector",
  "attr_matcher",
  "any_value",
  "an_plus_b",
  "relative_selector_list",
  "relative_selector",
  "\"-group@COMMA-relative_selector\"",
  "\"-many@-group@COMMA-relative_selector\"" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_1(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 31)
  def _reduce_3(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_4(val, _values, result)
            result = Node.new(:selector_list, nil, @current_position)
        result.add_child(val[0])
        val[1].each { |pair| result.add_child(pair[1]) }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_5(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_6(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_7(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_8(val, _values, result)
            if val[1].empty?
          result = val[0]
        else
          result = val[0]
          val[1].each do |pair|
            node = Node.new(:selector, nil, result.position)
            node.add_child(result)
            node.add_child(pair[0])
            node.add_child(pair[1])
            result = node
          end
        end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_9(val, _values, result)
     result = Node.new(:child_combinator, '>', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_10(val, _values, result)
     result = Node.new(:adjacent_combinator, '+', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 56)
  def _reduce_11(val, _values, result)
     result = Node.new(:sibling_combinator, '~', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_12(val, _values, result)
     result = Node.new(:descendant_combinator, ' ', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_13(val, _values, result)
            result = Node.new(:simple_selector_sequence, nil, val[0].position)
        result.add_child(val[0])
        val[1].each { |sel| result.add_child(sel) } unless val[1].empty?

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_14(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_15(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_16(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 81)
  def _reduce_17(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_18(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_19(val, _values, result)
     result = Node.new(:type_selector, identifier_value(val[0]), @current_position, raw_value: identifier_raw(val[0]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 86)
  def _reduce_20(val, _values, result)
     result = Node.new(:universal_selector, '*', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 91)
  def _reduce_21(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 93)
  def _reduce_22(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_23(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 97)
  def _reduce_24(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 99)
  def _reduce_25(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 104)
  def _reduce_26(val, _values, result)
     result = Node.new(:id_selector, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_27(val, _values, result)
     result = Node.new(:class_selector, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 114)
  def _reduce_28(val, _values, result)
     result = Node.new(:attribute_selector, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 117)
  def _reduce_29(val, _values, result)
            result = Node.new(:attribute_selector, nil, @current_position)
        result.add_child(Node.new(:attribute, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1])))
        result.add_child(val[2])
        result.add_child(Node.new(:value, val[3], @current_position))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 124)
  def _reduce_30(val, _values, result)
            result = Node.new(:attribute_selector, nil, @current_position)
        result.add_child(Node.new(:attribute, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1])))
        result.add_child(val[2])
        result.add_child(Node.new(:value, identifier_value(val[3]), @current_position, raw_value: identifier_raw(val[3])))

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_31(val, _values, result)
     result = Node.new(:equal_operator, '=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 135)
  def _reduce_32(val, _values, result)
     result = Node.new(:includes_operator, '~=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 137)
  def _reduce_33(val, _values, result)
     result = Node.new(:dashmatch_operator, '|=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 139)
  def _reduce_34(val, _values, result)
     result = Node.new(:prefixmatch_operator, '^=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 141)
  def _reduce_35(val, _values, result)
     result = Node.new(:suffixmatch_operator, '$=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 143)
  def _reduce_36(val, _values, result)
     result = Node.new(:substringmatch_operator, '*=', @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 148)
  def _reduce_37(val, _values, result)
     result = Node.new(:pseudo_class, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_38(val, _values, result)
            fn = Node.new(:pseudo_function, identifier_value(val[1]), @current_position, raw_value: identifier_raw(val[1]))
        fn.add_child(val[3])
        result = fn

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 157)
  def _reduce_39(val, _values, result)
            fn = Node.new(:pseudo_function, identifier_value(val[0]), @current_position, raw_value: identifier_raw(val[0]))
        fn.add_child(val[2])
        result = fn

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_40(val, _values, result)
     result = Node.new(:pseudo_element, identifier_value(val[2]), @current_position, raw_value: identifier_raw(val[2]))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 170)
  def _reduce_41(val, _values, result)
     result = Node.new(:argument, val[0], @current_position)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 172)
  def _reduce_42(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 174)
  def _reduce_43(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 181)
  def _reduce_44(val, _values, result)
            # Handle 'An+B' like '2n+1'
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}+#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 186)
  def _reduce_45(val, _values, result)
            # Handle 'An-B' like '2n-1'
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}-#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 191)
  def _reduce_46(val, _values, result)
            # Handle 'An' like '2n' or composite like '2n-1' (when '-1' is part of IDENT)
        result = Node.new(:an_plus_b, "#{val[0]}#{val[1]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 196)
  def _reduce_47(val, _values, result)
            # Handle 'n+B' like 'n+5' or keywords followed by offset (rare but valid)
        result = Node.new(:an_plus_b, "#{val[0]}+#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 201)
  def _reduce_48(val, _values, result)
            # Handle 'n-B' like 'n-3'
        result = Node.new(:an_plus_b, "#{val[0]}-#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 207)
  def _reduce_49(val, _values, result)
            # Handle '-An+B' like '-2n+1'
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}+#{val[4]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 212)
  def _reduce_50(val, _values, result)
            # Handle '-An-B' like '-2n-1'
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}-#{val[4]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 217)
  def _reduce_51(val, _values, result)
            # Handle '-An' like '-2n' or composite like '-2n+1' (when '+1' is part of IDENT)
        result = Node.new(:an_plus_b, "-#{val[1]}#{val[2]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 222)
  def _reduce_52(val, _values, result)
            # Handle '-n+B' like '-n+3'
        result = Node.new(:an_plus_b, "-#{val[1]}+#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 227)
  def _reduce_53(val, _values, result)
            # Handle '-n-B' like '-n-2'
        result = Node.new(:an_plus_b, "-#{val[1]}-#{val[3]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 232)
  def _reduce_54(val, _values, result)
            # Handle '-n' or composite like '-n+3' (when '+3' is part of IDENT)
        result = Node.new(:an_plus_b, "-#{val[1]}", @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 238)
  def _reduce_55(val, _values, result)
            # Handle just a number like '3'
        result = Node.new(:an_plus_b, val[0].to_s, @current_position)

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_56(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_57(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_58(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 246)
  def _reduce_59(val, _values, result)
            result = Node.new(:selector_list, nil, @current_position)
        result.add_child(val[0])
        val[1].each { |pair| result.add_child(pair[1]) }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 254)
  def _reduce_60(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 257)
  def _reduce_61(val, _values, result)
            result = Node.new(:selector, nil, val[0].position)
        result.add_child(val[0])
        result.add_child(val[1])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module Parselly
